### PR TITLE
Update attention template

### PR DESCRIPTION
**Pull request by manupak**
Ths commit updates the attention
template to include promote operands
and decomposition_config.

### CODE REVIEW

**Review by Groverkss — APPROVED** [review]
Thank you!

**Comment by saienduri** [comment]
Thanks, can you also change this line https://github.com/nod-ai/iree-kernel-benchmark/blob/main/.github/workflows/run_bench.yml#L19 to `mi300-sdxl-kernel`, so a runner gets picked up for CI

**Comment by manupak** [comment]
Thanks @saienduri can you "suggest" the change? .. so that I can commit it :). I need to setup ssh on the machine im currently in to change a workflow as PAT does not allow that.

**Comment by manupak** [comment]
nvm let me setup ssh... I dont think you can suggest as it is not changed in the PR.

**Comment by saienduri** [comment]
Cool, you can also just use the github UI and edit the file on your branch if it's too much trouble

**Comment by manupak** [comment]
@saienduri thanks for the tip! i did not know about GH UI :o

**Review by saienduri — APPROVED** [review]

**Comment by manupak** [comment]
@saienduri as first timer here, who should merge the PR :) ?

**Comment by saienduri** [comment]
Once you get an approval, go for it :). Merging it now though

**Pull request merged**
